[workspace]
members = [
	"rust_1","factory1", "factory2", "prototype", "builder", "abstract-factory","vec_sort", "singleton_once","lazy_test",
	"strategy_1", "state","command1","iterator1","observer1","chain1", "visitor1", "mediator1", "moment1","adapter1",
	"bridge1", "composite1", "decorator1"
]